---
- name: install magerun | check if n98-magerun is already installed
  stat: path={{ magento_magerun_binary_path }}
  register: magerun

- name: install magerun | get magerun binary
  get_url: url={{ magento_magerun_binary_url }} dest={{ magento_magerun_binary_path }}
  when: not magerun.stat.exists

- name: install magerun | ensure magerun is executable
  file: path={{ magento_magerun_binary_path }} mode="ugo+x"
  when: magerun.stat.islnk is defined and magerun.stat.islnk == false

